services:
    contao.routing.permalink_url_generator:
        class: Agoat\PermalinkBundle\Routing\UrlGenerator
        decorates: contao.routing.url_generator
        arguments:
            - "@router"
            - "@contao.controller.chain"
            - "%contao.prepend_locale%"

    contao.routing.guid_loader:
        class: Agoat\PermalinkBundle\Routing\GuidControllerLoader
        decorates: contao.routing.frontend_loader
        public: false
        arguments:
            - "%contao.prepend_locale%"
        tags:
            - { name: routing.loader }

    contao.controller.chain:
        class: Agoat\PermalinkBundle\Controller\ControllerChain

    contao.controller.page:
        class: Agoat\PermalinkBundle\Controller\PageController
        public: false
        arguments:
            - "@router"
        tags:
            - { name: permalink.controller, context: page }

    contao.controller.article:
        class: Agoat\PermalinkBundle\Controller\ArticleController
        public: false
        tags:
            - { name: permalink.controllerx, context: articles }
            
    contao.controller.news:
        class: Agoat\PermalinkBundle\Controller\NewsController
        public: false
        tags:
            - { name: permalink.controllerx, context: items }
            
    contao.controller.event:
        class: Agoat\PermalinkBundle\Controller\EventController
        public: false
        tags:
            - { name: permalink.controller, context: events }
            
    contao.permalink.generator:
        class: Agoat\PermalinkBundle\Permalink\PermalinkGenerator
            
    contao.permalink.page:
        class: Agoat\PermalinkBundle\Permalink\PagePermalinkProvider
        public: false
        arguments:
            - "%contao.url_suffix%"
        tags:
            - { name: permalink.provider, context: page }
            
    contao.permalink.event:
        class: Agoat\PermalinkBundle\Permalink\EventPermalinkProvider
        public: false
        arguments:
            - "%contao.url_suffix%"
        tags:
            - { name: permalink.provider, context: events }
            
