services:
    contao.routing.permalink_url_generator:
        class: Agoat\PermalinkBundle\Routing\UrlGenerator
        decorates: contao.routing.url_generator
        arguments:
            - "@router"
            - "@contao.controller.chain"

    contao.routing.guid_loader:
        class: Agoat\PermalinkBundle\Routing\PermalinkLoader
        decorates: contao.routing.frontend_loader
        public: false
        tags:
            - { name: routing.loader }

    contao.controller.chain:
        class: Agoat\PermalinkBundle\Controller\ControllerChain

    contao.controller.page:
        class: Agoat\PermalinkBundle\Controller\PageController
        public: false
        arguments:
            - "@router"
        tags:
            - { name: permalink.controller, context: page }

    contao.controller.items:
        class: Agoat\PermalinkBundle\Controller\ItemsController
        public: false
        tags:
            - { name: permalink.controller, context: items }
            
    contao.controller.events:
        class: Agoat\PermalinkBundle\Controller\EventsController
        public: false
        tags:
            - { name: permalink.controller, context: events }
            
    contao.permalink.generator:
        class: Agoat\PermalinkBundle\Permalink\PermalinkGenerator
            
    contao.permalink.page:
        class: Agoat\PermalinkBundle\Permalink\PagePermalinkProvider
        public: false
        arguments:
            - "%contao.url_suffix%"
        tags:
            - { name: permalink.provider, context: page }
            
    contao.permalink.items:
        class: Agoat\PermalinkBundle\Permalink\ItemsPermalinkProvider
        public: false
        arguments:
            - "%contao.url_suffix%"
        tags:
            - { name: permalink.provider, context: items }
            
            
    contao.permalink.events:
        class: Agoat\PermalinkBundle\Permalink\EventsPermalinkProvider
        public: false
        arguments:
            - "%contao.url_suffix%"
        tags:
            - { name: permalink.provider, context: events }
