services:
    permalink.routing.url_generator:
        class: Agoat\PermalinkBundle\Routing\UrlGenerator
        decorates: contao.routing.url_generator
        arguments:
            - "@router"
            - "@contao.framework"
            - "%contao.prepend_locale%"
            - "@permalink.routing.url_generator.inner"

    permalink.routing.guid_loader:
        class: Agoat\PermalinkBundle\Routing\GuidControllerLoader
        decorates: contao.routing.frontend_loader
        public: false
        arguments:
            - "%contao.prepend_locale%"
        tags:
            - { name: routing.loader }

    permalink.frontend.controller.chain:
        class: Agoat\PermalinkBundle\Frontend\ControllerChain

    permalink.frontend.controller.page:
        class: Agoat\PermalinkBundle\Frontend\PageController
        public: false
        arguments:
            - "@router"
        tags:
            - { name: permalink.controller, context: page }

    permalink.frontend.controller.article:
        class: Agoat\PermalinkBundle\Frontend\ArticleController
        public: false
        tags:
            - { name: permalink.controllerx, context: articles }
            
    permalink.frontend.controller.news:
        class: Agoat\PermalinkBundle\Frontend\NewsController
        public: false
        tags:
            - { name: permalink.controllerx, context: items }
            
    permalink.frontend.controller.event:
        class: Agoat\PermalinkBundle\Frontend\EventController
        public: false
        tags:
            - { name: permalink.controller, context: events }
            
