services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Contao\CoreBundle\Framework\ContaoFramework: "@contao.framework"

    _instanceof:
        Agoat\PermalinkBundle\Permalink\PermalinkHandlerInterface:
            bind:
                $requestStack: "@request_stack"
                $suffix: "%contao.url_suffix%"
            tags: [ 'permalink.handler' ]

    Agoat\PermalinkBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources,ContaoManager}'

    Agoat\PermalinkBundle\EventListener\DataContainer\:
        resource: '../../EventListener/DataContainer/*'
        public: true

    Agoat\PermalinkBundle\Routing\RouteProvider:
        decorates: contao.routing.route_provider

    Agoat\PermalinkBundle\Routing\RouteLoader:
        decorates: contao.routing.frontend_loader

    Agoat\PermalinkBundle\Routing\UrlGenerator:
        decorates: contao.routing.url_generator
        arguments:
            - "@router"

    Agoat\PermalinkBundle\Permalink\Permalink:
        public: true
        arguments:
            - !tagged { tag: permalink.handler }

    Agoat\PermalinkBundle\Permalink\PagePermalinkHandler:
        tags:
            - { name: permalink.handler, priority: 10 }
